// Generated by https://quicktype.io

export interface HorariosResponse {
    total:   number;
    horarios: Horario[];
}

export interface Horario {
    id:          string;
    dia_hora:    string;
    numero_ruta: number;
    id_ruta:     string;
}
