// Generated by https://quicktype.io

export interface NotificacionesResponse {
    notificaiones: Notificaion[];
}

export interface Notificaion {
    id:         string;
    hora:       number;
    minuto:     number;
    horario:    string;
    id_usuario: string;
    id_ruta:    string;
    fk_ruta:    FkRuta;
}

export interface FkRuta {
    id:      string;
    numero:  number;
    destino: string;
    origen:  string;
    estado:  boolean;
}
