// Generated by https://quicktype.io

export interface RutasResponse {
    total: number;
    rutas: Ruta[];
}

export interface Ruta {
    id:      string;
    numero:  number;
    destino: string;
    origen:  string;
    estado:  boolean;
}
