// Generated by https://quicktype.io

export interface UserAuthenticatedInterface {
    user:  User;
    token: string;
}

export interface User {
    id:        string;
    correo:    string;
    nombre:    string;
    apellidos: string;
    password:  string;
    telefono:  string;
    foto:      string;
    estado:    boolean;
    rol:       string;
}
